담벼락 좋아요/취소 API 개선
chanoo/klock-api pull request #71
Opened 2024-02-29 03:21 UTC by foxsea

2024-02-29 04:11 UTC, chanoo requested changes

2024-02-29 04:11 UTC, chanoo commented on src/main/kotlin/app/klock/api/functional/userTrace/UserTraceRouter.kt
> +      PUT("/{trace_id}/heart/cancel", userTraceHandler::cancelHeart)
메소드로 구분하는게 좋을것 같습니다 
```kotlin
DELETE("/{trace_id}/heart", userTraceHandler::cancelHeart)
```

2024-02-29 04:11 UTC, chanoo commented on src/main/kotlin/app/klock/api/service/UserTraceHeartService.kt
> +        heartCount = 1
heartCount 는 앱에서 같이 보냅니다

2024-02-29 04:11 UTC, chanoo commented on src/main/kotlin/app/klock/api/functional/userTrace/UserTraceHandler.kt
> +            userTraceService.updateHeart(traceId, 1)
userId에 1은 어떤 의미인가요?

2024-02-29 04:56 UTC, foxsea commented on src/main/kotlin/app/klock/api/functional/userTrace/UserTraceRouter.kt
> +      PUT("/{trace_id}/heart/cancel", userTraceHandler::cancelHeart)
데이터 상으로도 삭제가 아니라 취소하는거라 이렇게 한건데
실제 삭제를 api 로 사용할 일은 없어 보이니 그렇게 수정하겠음

2024-02-29 06:12 UTC, foxsea commented on src/main/kotlin/app/klock/api/service/UserTraceHeartService.kt
> +        heartCount = 1
취소시에는 한건씩 삭제하고 추가시에는 카운트를 보내는걸로 하겠다는건가?

2024-02-29 06:12 UTC, foxsea commented on src/main/kotlin/app/klock/api/functional/userTrace/UserTraceHandler.kt
> +            userTraceService.updateHeart(traceId, 1)
userId가 아니고 하트 카운트 수임.
이걸 앱에서 받는걸로 바꿀 예정

2024-03-01 02:14 UTC, chanoo approved these changes

2024-03-04 07:22 UTC, merged